// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWsmTrZBzmU8ETVMbpz1qr_nW49RT-uNs',
    appId: '1:955126995305:web:7d25a0f89c06841ed745f8',
    messagingSenderId: '955126995305',
    projectId: 'margdarshak-e0738',
    authDomain: 'margdarshak-e0738.firebaseapp.com',
    storageBucket: 'margdarshak-e0738.appspot.com',
    measurementId: 'G-Y6CKGBKM1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCiFWCXhzJ5dJT7B5CwXvohwKS6K3q9wg',
    appId: '1:955126995305:android:d7ba0c3382558d85d745f8',
    messagingSenderId: '955126995305',
    projectId: 'margdarshak-e0738',
    storageBucket: 'margdarshak-e0738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOlTD5D4C6Ygkv_CWM_LTN1PicAHMywk',
    appId: '1:955126995305:ios:27c04fca887ca614d745f8',
    messagingSenderId: '955126995305',
    projectId: 'margdarshak-e0738',
    storageBucket: 'margdarshak-e0738.appspot.com',
    iosClientId: '955126995305-5bdrd08vo9fji3dmu9e4f0cjmgnq8rnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOlTD5D4C6Ygkv_CWM_LTN1PicAHMywk',
    appId: '1:955126995305:ios:c72bb126b01a7f0bd745f8',
    messagingSenderId: '955126995305',
    projectId: 'margdarshak-e0738',
    storageBucket: 'margdarshak-e0738.appspot.com',
    iosClientId: '955126995305-808ivsjtc6i19b4mc3blvjg2t2tsskj8.apps.googleusercontent.com',
    iosBundleId: 'com.margdarshak.app',
  );
}
